# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always


# Spring Configuration
spring:
  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/rentalhive?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  liquibase:
    enabled: false
  main:
    lazy-initialization: true

logging:
  file:
    name: myLogs.log
